

services:
  mysql-db:
    image: mysql:8.0.1
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: BDLeilao
      MYSQL_USER:  user
      MYSQL_PASSWORD: leilaopass
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password


volumes:
  mysql_data:
