version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-leilao
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: leilao
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
